main = "src/worker.ts"
compatibility_date = "2024-04-19"

# The worker defaults to staging URL's unless you include --var in your cli command
[vars]
ENVIRONMENT = "localhost"
# Naming convention <domain>_API_<brand> or <region>
AUTH_API_BLC_UK = "https://staging-auth.blcshine.io"
AUTH_API_BLC_AU = "https://staging-auth-au.blcshine.io"
AUTH_API_DDS_UK = "https://staging-auth-dds.blcshine.io"
IDENTITY_API_BLC_UK = "https://staging-identity.blcshine.io"
IDENTITY_API_BLC_AU = "https://staging-identity-au.blcshine.io"
IDENTITY_API_DDS_UK = "https://staging-identity.blcshine.io"
OFFERS_API_BLC_UK = "https://staging-offers.blcshine.io"
OFFERS_API_BLC_AU = "https://staging-offers-au.blcshine.io"
OFFERS_API_DDS_UK = "https://staging-offers-dds-uk.blcshine.io"
OFFERS_CMS_API_BLC_UK = "https://p8xx1rb6qh.execute-api.eu-west-2.amazonaws.com"
OFFERS_CMS_API_BLC_AU = "https://lvdufnuqma.execute-api.ap-southeast-2.amazonaws.com"
OFFERS_CMS_API_DDS_UK = "https://y86fnqmne0.execute-api.eu-west-2.amazonaws.com"
REDEMPTIONS_API_BLC_UK = "https://staging-redemptions.blcshine.io"
REDEMPTIONS_API_BLC_AU = "https://staging-redemptions-blc-au.blcshine.io"
REDEMPTIONS_API_DDS_UK = "https://staging-redemptions-dds-uk.blcshine.io"

ORDERS_API_BLC_UK = "https://staging-orders-blc-uk.blcshine.io"
ORDERS_API_BLC_AU = "https://staging-orders-blc-au.blcshine.io"
ORDERS_API_DDS_UK = "https://staging-orders-dds-uk.blcshine.io"

DISCOVERY_API_BLC_UK = "https://staging-discovery.blcshine.io"
DISCOVERY_API_BLC_AU = "https://staging-discovery.blcshine.io"
DISCOVERY_API_DDS_UK = "https://staging-discovery.blcshine.io"

[env.pr.vars]
ENVIRONMENT = "pr"
AUTH_API_BLC_UK = "https://staging-auth.blcshine.io"
AUTH_API_BLC_AU = "https://staging-auth-au.blcshine.io"
AUTH_API_DDS_UK = "https://staging-auth-dds.blcshine.io"
IDENTITY_API_BLC_UK = "https://staging-identity.blcshine.io"
IDENTITY_API_BLC_AU = "https://staging-identity-au.blcshine.io"
IDENTITY_API_DDS_UK = "https://staging-identity.blcshine.io"
OFFERS_API_BLC_UK = "https://staging-offers.blcshine.io"
OFFERS_API_BLC_AU = "https://staging-offers-au.blcshine.io"
OFFERS_API_DDS_UK = "https://staging-offers-dds-uk.blcshine.io"
OFFERS_CMS_API_BLC_UK = "https://p8xx1rb6qh.execute-api.eu-west-2.amazonaws.com"
OFFERS_CMS_API_BLC_AU = "https://lvdufnuqma.execute-api.ap-southeast-2.amazonaws.com"
OFFERS_CMS_API_DDS_UK = "https://y86fnqmne0.execute-api.eu-west-2.amazonaws.com"
REDEMPTIONS_API_BLC_UK = "https://staging-redemptions.blcshine.io"
REDEMPTIONS_API_BLC_AU = "https://staging-redemptions-blc-au.blcshine.io"
REDEMPTIONS_API_DDS_UK = "https://staging-redemptions-dds-uk.blcshine.io"
ORDERS_API_BLC_UK = "https://staging-orders-blc-uk.blcshine.io"
ORDERS_API_BLC_AU = "https://staging-orders-blc-au.blcshine.io"
ORDERS_API_DDS_UK = "https://staging-orders-dds-uk.blcshine.io"
DISCOVERY_API_BLC_UK = "https://staging-discovery.blcshine.io"
DISCOVERY_API_BLC_AU = "https://staging-discovery.blcshine.io"
DISCOVERY_API_DDS_UK = "https://staging-discovery.blcshine.io"

[env.staging.vars]
ENVIRONMENT = "staging"
# Naming convention <domain>_API_<brand> or <region>
AUTH_API_BLC_UK = "https://staging-auth.blcshine.io"
AUTH_API_BLC_AU = "https://staging-auth-au.blcshine.io"
AUTH_API_DDS_UK = "https://staging-auth-dds.blcshine.io"
IDENTITY_API_BLC_UK = "https://staging-identity.blcshine.io"
IDENTITY_API_BLC_AU = "https://staging-identity-au.blcshine.io"
IDENTITY_API_DDS_UK = "https://staging-identity.blcshine.io"
OFFERS_API_BLC_UK = "https://staging-offers.blcshine.io"
OFFERS_API_BLC_AU = "https://staging-offers-au.blcshine.io"
OFFERS_API_DDS_UK = "https://staging-offers-dds-uk.blcshine.io"
OFFERS_CMS_API_BLC_UK = "https://p8xx1rb6qh.execute-api.eu-west-2.amazonaws.com"
OFFERS_CMS_API_BLC_AU = "https://lvdufnuqma.execute-api.ap-southeast-2.amazonaws.com"
OFFERS_CMS_API_DDS_UK = "https://y86fnqmne0.execute-api.eu-west-2.amazonaws.com"
REDEMPTIONS_API_BLC_UK = "https://staging-redemptions.blcshine.io"
REDEMPTIONS_API_BLC_AU = "https://staging-redemptions-blc-au.blcshine.io"
REDEMPTIONS_API_DDS_UK = "https://staging-redemptions-dds-uk.blcshine.io"
ORDERS_API_BLC_UK = "https://staging-orders-blc-uk.blcshine.io"
ORDERS_API_BLC_AU = "https://staging-orders-blc-au.blcshine.io"
ORDERS_API_DDS_UK = "https://staging-orders-dds-uk.blcshine.io"
DISCOVERY_API_BLC_UK = "https://staging-discovery.blcshine.io"
DISCOVERY_API_BLC_AU = "https://staging-discovery.blcshine.io"
DISCOVERY_API_DDS_UK = "https://staging-discovery.blcshine.io"

[env.production.vars]
ENVIRONMENT = "production"
# Naming convention <domain>_API_<brand> or <region>
AUTH_API_BLC_UK = "https://auth.blcshine.io"
AUTH_API_BLC_AU = "https://auth-au.blcshine.io"
AUTH_API_DDS_UK = "https://auth-dds.blcshine.io"
IDENTITY_API_BLC_UK = "https://identity.blcshine.io"
IDENTITY_API_BLC_AU = "https://identity-au.blcshine.io"
IDENTITY_API_DDS_UK = "https://identity.blcshine.io"
OFFERS_API_BLC_UK = "https://offers.blcshine.io"
OFFERS_API_BLC_AU = "https://offers-au.blcshine.io"
OFFERS_API_DDS_UK = "https://offers-dds-uk.blcshine.io"
# TODO: Swap the following 3 for the offers cms stack's url
OFFERS_CMS_API_BLC_UK = "https://offers.blcshine.io"
OFFERS_CMS_API_BLC_AU = "https://offers-au.blcshine.io"
OFFERS_CMS_API_DDS_UK = "https://offers-dds-uk.blcshine.io"
REDEMPTIONS_API_BLC_UK = "https://redemptions.blcshine.io"
REDEMPTIONS_API_BLC_AU = "https://redemptions-blc-au.blcshine.io"
REDEMPTIONS_API_DDS_UK = "https://redemptions-dds-uk.blcshine.io"
ORDERS_API_BLC_UK = "https://orders-blc-uk.blcshine.io"
ORDERS_API_BLC_AU = "https://orders-blc-au.blcshine.io"
ORDERS_API_DDS_UK = "https://orders-dds-uk.blcshine.io"
DISCOVERY_API_BLC_UK = "https://discovery.blcshine.io"
DISCOVERY_API_BLC_AU = "https://discovery.blcshine.io"
DISCOVERY_API_DDS_UK = "https://discovery.blcshine.io"

[env.pr]
name = "pr-api"
main = "src/pr/pr-worker.ts"
workers_dev = true

[env.staging]
name = "staging-api"
workers_dev = true

[env.production]
name = "api"
workers_dev = true
