export enum MemberStackEnvironmentKeys {
  SKIP_MEMBERS_STACK = 'SKIP_MEMBERS_STACK',
  // CORS
  API_DEFAULT_ALLOWED_ORIGINS = 'API_DEFAULT_ALLOWED_ORIGINS',

  // S3
  ID_UPLOAD_BUCKET = 'ID_UPLOAD_BUCKET',
  // DATADOG
  USE_DATADOG_AGENT = 'false', // # 'true' or 'false'
  DD_API_KEY = '',
  DD_GIT_COMMIT_SHA = '',
  DD_GIT_REPOSITORY_URL = 'https://github.com/bluelightcard/BlueLightCard-2.0',
  DD_VERSION = '',
  MEMBER_PROFILE_TABLE_NAME = 'MEMBER_PROFILE_TABLE_NAME',

  // BRAZE
  BRAZE_SERVICE_JSON = 'BRAZE_SERVICE_JSON',

  // EMAIL
  MEMBERS_EMAIL_FROM = 'MEMBERS_EMAIL_FROM',

  // AUTH0
  SERVICE_LAYER_AUTH0_DOMAIN = 'SERVICE_LAYER_AUTH0_DOMAIN',
  SERVICE_LAYER_AUTH0_API_CLIENT_ID = 'SERVICE_LAYER_AUTH0_API_CLIENT_ID',
  SERVICE_LAYER_AUTH0_API_CLIENT_SECRET = 'SERVICE_LAYER_AUTH0_API_CLIENT_SECRET',
  SERVICE_LAYER_AUTH0_PASSWORD_VALIDATION_CLIENT_ID = 'SERVICE_LAYER_AUTH0_PASSWORD_VALIDATION_CLIENT_ID',
  SERVICE_LAYER_AUTH0_PASSWORD_VALIDATION_CLIENT_SECRET = 'SERVICE_LAYER_AUTH0_PASSWORD_VALIDATION_CLIENT_SECRET',

  // STACK
  SERVICE = 'SERVICE',
  STAGE = 'STAGE',

  // OPEN SEARCH
  OPENSEARCH_DOMAIN_ENDPOINT = 'OPENSEARCH_DOMAIN_ENDPOINT',
}
