name: Clean PR Comments
description: Clean bot comments from PR based on string search
inputs:
  GITHUB_TOKEN:
    description: Value from secrets.GITHUB_TOKEN
    required: true
  searchString:
    description: Search string to identify comments to delete
    required: true

runs:
  using: composite
  steps:
    - name: Clean
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.GITHUB_TOKEN }}
        script: |
          // 1. Retrieve existing bot comments for the PR
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });
          // 2. Find all comments matching search criteria
          const botComments = comments.filter(comment => {
            return comment.user.type === 'Bot' && comment.body.includes('${{ inputs.searchString }}')
          });
          // 3. Delete all matching comments
          botComments?.forEach(botComment => {
            github.rest.issues.deleteComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
            });
            console.log('Deleted comment id: ' + botComment.id)
          });
