export const OffersCMSStackEnvironmentKeys = {
  COGNITO_CLIENT_ID: 'OFFERS_CMS_COGNITO_CLIENT_ID',
  COGNITO_CLIENT_SECRET: 'OFFERS_CMS_COGNITO_CLIENT_SECRET',
  COGNITO_IDP_ID: 'OFFERS_CMS_COGNITO_IDP_ID',
  DISCOVERY_EVENT_BUS_NAME: 'OFFERS_CMS_DISCOVERY_EVENT_BUS_NAME',
  CMS_ACCOUNT: 'OFFERS_CMS_CMS_ACCOUNT',
};
