export const OffersCMSStackEnvironmentKeys = {
  OFFERS_CMS_COGNITO_CLIENT_ID: 'OFFERS_CMS_COGNITO_CLIENT_ID',
  OFFERS_CMS_COGNITO_CLIENT_SECRET: 'OFFERS_CMS_COGNITO_CLIENT_SECRET',
  OFFERS_CMS_COGNITO_IDP_ID: 'OFFERS_CMS_COGNITO_IDP_ID',
  OFFERS_BRAND: 'OFFERS_BRAND',
  DISCOVERY_EVENT_BUS_NAME: 'DISCOVERY_EVENT_BUS_NAME',
  DISCOVERY_EVENT_BUS_ID: 'DISCOVERY_EVENT_BUS_ID',
};
