name: 'Setup'
description: 'Setup the repository for the rest of the workflow'
inputs:
  restore_cache:
    description: 'Restore cache'
    required: true
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc

    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v4
      with:
        # If inputs.restore_cache is set to false, set lookup-only to true
        lookup-only: ${{ !fromJSON(inputs.restore_cache) }}
        path: '**/node_modules'
        key: ${{ runner.os }}-${{ runner.arch }}-node_modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-${{ runner.arch }}-node_modules-

    - name: Install Local Font Awesome
      shell: 'bash'
      run: npm run fontawesome:fix

    - name: Install Dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      shell: 'bash'
      run: npm install

    - if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: NPM Logs
        path: /home/runner/.npm/_logs/
