version: '3.8'

services:

  # Dockerize the application

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    env_file:
      - .env
    networks:
      - default
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    driver: local

networks:
  default: