main = ".worker-next/index.mjs"
name = "__PROJECT_NAME_PLACEHOLDER__"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".worker-next/assets", binding = "ASSETS" }

workers_dev = true
preview_urls = true

[[kv_namespaces]]
binding = "NEXT_CACHE_WORKERS_KV"
id = "__KV_NAMESPACE_ID_PLACEHOLDER__"