export enum DiscoveryStackEnvironmentKeys {
  // Lambda scripts integration
  SKIP_DISCOVERY_STACK = 'SKIP_DISCOVERY_STACK',
  SEARCH_LAMBDA_SCRIPTS_HOST = 'SEARCH_LAMBDA_SCRIPTS_HOST',
  SEARCH_LAMBDA_SCRIPTS_ENVIRONMENT = 'SEARCH_LAMBDA_SCRIPTS_ENVIRONMENT',
  SEARCH_BRAND = 'SEARCH_BRAND',
  SEARCH_AUTH_TOKEN_OVERRIDE = 'SEARCH_AUTH_TOKEN_OVERRIDE',
  SEARCH_DOMAIN_HOST = 'SEARCH_DOMAIN_HOST',
  // CORS
  API_DEFAULT_ALLOWED_ORIGINS = 'API_DEFAULT_ALLOWED_ORIGINS',
  // OPEN SEARCH
  OPENSEARCH_STAGING_DOMAIN_ENDPOINT = 'OPENSEARCH_STAGING_DOMAIN_ENDPOINT',
}
