export enum DiscoveryStackEnvironmentKeys {
  // Lambda scripts integration
  SEARCH_LAMBDA_SCRIPTS_HOST = 'SEARCH_LAMBDA_SCRIPTS_HOST',
  SEARCH_LAMBDA_SCRIPTS_ENVIRONMENT = 'SEARCH_LAMBDA_SCRIPTS_ENVIRONMENT',
  SEARCH_BRAND = 'SEARCH_BRAND',
  SEARCH_AUTH_TOKEN_OVERRIDE = 'SEARCH_AUTH_TOKEN_OVERRIDE',
  // CORS
  API_DEFAULT_ALLOWED_ORIGINS = 'API_DEFAULT_ALLOWED_ORIGINS',
}
