export enum PaymentStatus {
  AWAITING_PAYMENT = 'AWAITING_PAYMENT',
  PAID_CARD = 'PAID_CARD',
  PAID_PAYPAL = 'PAID_PAYPAL',
  PAID_PROMO_CODE = 'PAID_PROMO_CODE',
  PAID_CHEQUE = 'PAID_CHEQUE',
  PAID_ADMIN = 'PAID_ADMIN',
  PENDING_REFUND = 'PENDING_REFUND',
  REFUNDED = 'REFUNDED',
  AWAITING_PAYMENT_CONFIRMATION = 'AWAITING_PAYMENT_CONFIRMATION',
}
