export enum LoginAudit {
   WEB_LOGIN = 1,
   APP_LOGIN = 2,
   WEB_REFRESH_TOKEN = 3,
   APP_REFRESH_TOKEN = 4,
   WEB_HOSTEDUI_LOGIN = 5,
   APP_HOSTEDUI_LOGIN = 6,
   REWARD_GATEWAY_REFRESH_TOKEN = 7.1,
   REWARD_GATEWAY_HOSTEDUI_LOGIN = 8.1,
   YALSON_REFRESH_TOKEN = 7.2,
   YALSON_HOSTEDUI_LOGIN = 8.2
};

export enum LOGIN_CLIENT_TYPE {
   WEB = "WEB",
   APP = "APP",
   WEB_HOSTEDUI = "WEB_HOSTEDUI",
   APP_HOSTEDUI = "APP_HOSTEDUI",
   REWARD_GATEWAY = "REWARD_GATEWAY",
   YALSON = "YALSON",
};

// Map for LOGIN_CLIENT_TYPE & LoginAuditValue
// This should have 2 values for each LOGIN_CLIENT_TYPE
// i.e  LOGIN_CLIENT_TYPE_LOGIN & LOGIN_CLIENT_TYPE_REFRESH_TOKEN
export const CLIENT_NAME_LOGIN_AUDIT_MAP: any =
{
   "WEB_LOGIN": LoginAudit.WEB_LOGIN,
   "WEB_REFRESH_TOKEN": LoginAudit.WEB_REFRESH_TOKEN,
   "APP_LOGIN": LoginAudit.APP_LOGIN,
   "APP_REFRESH_TOKEN": LoginAudit.APP_REFRESH_TOKEN,
   "WEB_HOSTEDUI_LOGIN": LoginAudit.WEB_HOSTEDUI_LOGIN,
   "APP_HOSTEDUI_LOGIN": LoginAudit.APP_HOSTEDUI_LOGIN,
   "REWARD_GATEWAY_LOGIN": LoginAudit.REWARD_GATEWAY_HOSTEDUI_LOGIN,
   "REWARD_GATEWAY_REFRESH_TOKEN": LoginAudit.REWARD_GATEWAY_REFRESH_TOKEN,
   "YALSON_LOGIN": LoginAudit.YALSON_HOSTEDUI_LOGIN,
   "YALSON_REFRESH_TOKEN": LoginAudit.YALSON_REFRESH_TOKEN
};