export enum Auth0EventTypes {
  s = "Success Login",
  f = "Failed Login",
  w = "Warning During Login",
  fu = "Invalid Email/Username",
  fp = "Invalid Password", 
  slo = "Success Logout",
  scp = "Success Change Password",
  fcp = "Failed Change Password",
  scpr = "Success Change Password Request",
  fcpr = "Failed Change Password Request",
  sce = "Success Change Email",
  fce = "Failed Change Email",
  fvr = "Failed Verification Email Request",
  svr = "Success Verification Email Request",
  gd_auth_email_verification = "Success Email Verification",
  gd_auth_fail_email_verification = "Failed Email Verification",
  refresh_token_exchange_for_session_token_successful = "Success Refresh Token for Session Token",
  refresh_token_exchange_for_session_token_failed = "Failed Refresh Token for Session Token",
  fertft = "Failed Refresh Token",
  sertft = "Success Refresh Token",
}
