const events = {
  COMPANY_FILTER_CLICKED: 'company_filter_clicked',
  COMPANY_SHARED_CLICKED: 'company_share_clicked',
  COMPANY_VIEWED: 'company_viewed',
  EMAIL_CODE_CLICKED: 'email_vault_code_clicked',
  EMAIL_CODE_VIEWED: 'email_vault_code_viewed',
  GLOBAL_NAVIGATION_BROWSE_CATEGORIES_CLICKED: 'global_navigation_browse_categories_clicked',
  GLOBAL_NAVIGATION_MY_ACCOUNT_CLICKED: 'global_navigation_my_account_clicked',
  GLOBAL_NAVIGATION_MY_CARD_CLICKED: 'global_navigation_my_card_clicked',
  GLOBAL_NAVIGATION_NOTIFICATIONS_CLICKED: 'global_navigation_notifications_clicked',
  GLOBAL_NAVIGATION_OFFERS_CLICKED: 'global_navigation_offers_clicked',
  HOMEPAGE_VIEWED: 'homepage_viewed',
  OFFER_SHARE_CLICKED: 'offer_share_clicked',
  OFFER_TERMS_CLICKED: 'offer_terms_clicked',
  OFFER_VIEWED: 'offer_viewed',
  SEARCH_BY_CATEGORY_STARTED: 'search_by_category_started',
  SEARCH_BY_COMPANY_STARTED: 'search_by_company_started',
  SEARCH_BY_PHRASE_STARTED: 'search_by_phrase_started',
  SEARCH_RESULTS_CARD_CLICKED: 'search_results_card_clicked',
  SEARCH_RESULTS_VIEWED: 'search_results_list_viewed',
  SERP_SEARCH_STARTED: 'SERP_search_started',
  VAULT_CODE_REQUEST_CLICKED: 'vault_code_request_code_clicked',
  VAULT_CODE_REQUEST_VIEWED: 'vault_code_request_code_viewed',
};

export default events;
