export enum EnvironmentVariablesKeys {
  OFFERS_DATABASE_ROOT_PASSWORD = 'OFFERS_DATABASE_ROOT_PASSWORD',
  OFFERS_DATABASE_USER = 'OFFERS_DATABASE_USER',
  OFFERS_DATABASE_NAME = 'OFFERS_DATABASE_NAME',
  OFFERS_DATABASE_HOST = 'OFFERS_DATABASE_HOST',
  OFFERS_DATABASE_PORT = 'OFFERS_DATABASE_PORT',
  OFFERS_DATABASE_TYPE = 'OFFERS_DATABASE_TYPE',
  DATABASE_CONFIG = 'DATABASE_CONFIG',
  AWS_REGION = 'AWS_REGION',
}
