export enum RedemptionsStackEnvironmentKeys {
  // Database
  REDEMPTIONS_DATABASE_HOST = 'REDEMPTIONS_DATABASE_HOST',
  REDEMPTIONS_DATABASE_NAME = 'REDEMPTIONS_DATABASE_NAME',
  REDEMPTIONS_DATABASE_PASSWORD = 'REDEMPTIONS_DATABASE_PASSWORD',
  REDEMPTIONS_DATABASE_PORT = 'REDEMPTIONS_DATABASE_PORT',
  REDEMPTIONS_DATABASE_SEED_METHOD = 'REDEMPTIONS_DATABASE_SEED_METHOD',
  REDEMPTIONS_DATABASE_TYPE = 'REDEMPTIONS_DATABASE_TYPE',
  REDEMPTIONS_DATABASE_USER = 'REDEMPTIONS_DATABASE_USER',
  REDEMPTIONS_DANGEROUSLY_ALLOW_DATABASE_SETUP_STRATEGY = 'REDEMPTIONS_DANGEROUSLY_ALLOW_DATABASE_SETUP_STRATEGY',

  // Vault Redeem
  VAULT_REDEEM_ENVIRONMENT = 'REDEMPTIONS_RETRIEVE_ALL_ENVIRONMENT',
  VAULT_REDEEM_HOST = 'REDEMPTIONS_RETRIEVE_ALL_VAULTS_HOST',
  VAULT_REDEEM_PATH = 'REDEMPTIONS_RETRIEVE_ALL_VAULTS_PATH',

  // Integrations
  CODES_REDEEMED_ENVIRONMENT = 'CODES_REDEEMED_ENVIRONMENT',
  CODES_REDEEMED_HOST = 'CODES_REDEEMED_HOST',
  CODE_REDEEMED_PATH = 'CODE_REDEEMED_PATH',
  CODE_ASSIGNED_REDEEMED_PATH = 'CODE_ASSIGNED_REDEEMED_PATH',
  CODE_AMOUNT_ISSUED_PATH = 'CODE_AMOUNT_ISSUED_PATH',

  // CORS
  API_DEFAULT_ALLOWED_ORIGINS = 'API_DEFAULT_ALLOWED_ORIGINS',
}
