export enum Events {
  OFFER_CREATED = 'offer.created',
  OFFER_UPDATED = 'offer.updated',
  OFFER_DELETED = 'offer.deleted',
  COMPANY_CREATED = 'company.created',
  COMPANY_UPDATED = 'company.updated',
  MENU_OFFER_CREATED = 'menu.offer.created',
  MENU_OFFER_UPDATED = 'menu.offer.updated',
  MENU_OFFER_DELETED = 'menu.offer.deleted',
  MENU_COMPANY_CREATED = 'menu.company.created',
  MENU_COMPANY_UPDATED = 'menu.company.updated',
  MENU_COMPANY_DELETED = 'menu.company.deleted',
  MENU_CAMPAIGN_CREATED = 'menu.campaign.created',
  MENU_CAMPAIGN_UPDATED = 'menu.campaign.updated',
  MENU_CAMPAIGN_DELETED = 'menu.campaign.deleted',
  MENU_THEMED_OFFER_CREATED = 'menu.themed.offer.created',
  MENU_THEMED_OFFER_UPDATED = 'menu.themed.offer.updated',
  MENU_THEMED_OFFER_DELETED = 'menu.themed.offer.deleted',
  OPENSEARCH_POPULATE_INDEX = 'opensearch.populate.index',
}
