export enum Events {
  OFFER_CREATED = 'offer.created',
  OFFER_UPDATED = 'offer.updated',
  OFFER_DELETED = 'offer.deleted',
  EVENT_CREATED = 'event.created',
  EVENT_UPDATED = 'event.updated',
  EVENT_DELETED = 'event.deleted',
  COMPANY_CREATED = 'company.created',
  COMPANY_UPDATED = 'company.updated',
  COMPANY_DELETED = 'company.deleted',
  COMPANY_LOCATION_BATCH_CREATED = 'company.location.batch.created',
  COMPANY_LOCATION_BATCH_UPDATED = 'company.location.batch.updated',
  MARKETPLACE_MENUS_CREATED = 'menu.marketplace.created',
  MARKETPLACE_MENUS_UPDATED = 'menu.marketplace.updated',
  MARKETPLACE_MENUS_DELETED = 'menu.marketplace.deleted',
  DEALS_OF_THE_WEEK_CREATED = 'menu.dealsOfTheWeek.created',
  DEALS_OF_THE_WEEK_UPDATED = 'menu.dealsOfTheWeek.updated',
  DEALS_OF_THE_WEEK_DELETED = 'menu.dealsOfTheWeek.deleted',
  FEATURED_CREATED = 'menu.featuredOffers.created',
  FEATURED_UPDATED = 'menu.featuredOffers.updated',
  FEATURED_DELETED = 'menu.featuredOffers.deleted',
  WAYS_TO_SAVE_CREATED = 'menu.waysToSave.created',
  WAYS_TO_SAVE_UPDATED = 'menu.waysToSave.updated',
  WAYS_TO_SAVE_DELETED = 'menu.waysToSave.deleted',
  MENU_THEMED_OFFER_CREATED = 'menu.themed.offer.created',
  MENU_THEMED_OFFER_UPDATED = 'menu.themed.offer.updated',
  MENU_THEMED_OFFER_DELETED = 'menu.themed.offer.deleted',
  MENU_THEMED_EVENT_CREATED = 'menu.themed.event.created',
  MENU_THEMED_EVENT_UPDATED = 'menu.themed.event.updated',
  MENU_THEMED_EVENT_DELETED = 'menu.themed.event.deleted',
  OPENSEARCH_POPULATE_INDEX = 'opensearch.populate.index',
}

export enum MenuEventTypes {
  MARKETPLACE = 'menu.marketplace',
  DOTW = 'menu.dealsOfTheWeek',
  FEATURED = 'menu.featuredOffers',
  WAYS_TO_SAVE = 'menu.waysToSave',
  THEMED_MENUS = 'menu.themed.offer',
  THEMED_EVENTS = 'menu.themed.event',
}

export enum DetailTypes {
  INTEGRATION_TEST = 'test-event',
}
