import { DropdownOptions } from '@bluelightcard/shared-ui/components/Dropdown/types';

const ukCounties = [
  'Aberdeenshire',
  'Angus',
  'Antrim',
  'Argyll & Bute',
  'Armagh',
  'Ayrshire',
  'Banffshire',
  'Bedfordshire',
  'Berkshire',
  'Berwickshire',
  'Blaenau Gwent',
  'Bridgend',
  'Bristol',
  'Buckinghamshire',
  'Caerphilly',
  'Caithness',
  'Cambridgeshire',
  'Cardiff',
  'Carmarthenshire',
  'Ceredigion',
  'Cheshire',
  'Clackmannanshire',
  'Conwy',
  'Cornwall',
  'Cumbria',
  'Denbighshire',
  'Derbyshire',
  'Devon',
  'Dorset',
  'Down',
  'Dumfries & Galloway',
  'Durham',
  'East Ayrshire',
  'East Dunbartonshire',
  'East Lothian',
  'East Renfrewshire',
  'East Riding of Yorkshire',
  'East Sussex',
  'Essex',
  'Fermanagh',
  'Fife',
  'Flintshire',
  'Gloucestershire',
  'Greater London',
  'Greater Manchester',
  'Gwynedd',
  'Hampshire',
  'Herefordshire',
  'Hertfordshire',
  'Highland',
  'Inverclyde',
  'Isle of Anglesey',
  'Isle of Wight',
  'Kent',
  'Kincardineshire',
  'Lanarkshire',
  'Lancashire',
  'Leicestershire',
  'Lincolnshire',
  'Londonderry',
  'Merseyside',
  'Merthyr Tydfil',
  'Midlothian',
  'Monmouthshire',
  'Moray',
  'Neath Port Talbot',
  'Newport',
  'Norfolk',
  'North Ayrshire',
  'North Lanarkshire',
  'North Somerset',
  'North Yorkshire',
  'Northamptonshire',
  'Northumberland',
  'Nottinghamshire',
  'Orkney',
  'Oxfordshire',
  'Pembrokeshire',
  'Perth & Kinross',
  'Powys',
  'Renfrewshire',
  'Rhondda Cynon Taff',
  'Rutland',
  'Scottish Borders',
  'Shetland',
  'Shropshire',
  'Somerset',
  'South Ayrshire',
  'South Gloucestershire',
  'South Lanarkshire',
  'South Yorkshire',
  'Staffordshire',
  'Stirlingshire',
  'Suffolk',
  'Surrey',
  'Swansea',
  'Torfaen',
  'Tyne & Wear',
  'Tyrone',
  'Vale of Glamorgan',
  'Warwickshire',
  'West Dunbartonshire',
  'West Lothian',
  'West Midlands',
  'West Sussex',
  'West Yorkshire',
  'Western Isles',
  'Wiltshire',
  'Worcestershire',
  'Wrexham',
];
ukCounties.sort((left, right) => left.localeCompare(right));

export const ukCountyDropdownOptions: DropdownOptions = ukCounties.map((county) => ({
  id: county,
  label: county,
}));
