config:
  phases:
    - duration: 10
      arrivalRate: 1
      rampTo: 5
      name: Warm up phase
    - duration: 10
      arrivalRate: 5
      rampTo: 10
      name: Ramp up load
    - duration: 5
      arrivalRate: 10
      rampTo: 30
      name: Spike phase
  engines:
    playwright: {}
  plugins:
    ensure: {}
    metrics-by-endpoint: {}
  ensure:
    thresholds:
      - http.response_time.p99: 250
      - http.response_time.p95: 100

  processor: "./js/playwright-functions.js"

scenarios:
  - name: Member Home Page
    engine: playwright
    flowFunction: "loginAndGoToMemberHomepage"
