export enum CardStatus {
  AWAITING_BATCHING = 'AWAITING_BATCHING',
  ADDED_TO_BATCH = 'ADDED_TO_BATCH',
  CARD_BATCHED = 'CARD_BATCHED',
  CARD_PRINTED = 'CARD_PRINTED',
  AWAITING_POSTAGE = 'AWAITING_POSTAGE',
  PHYSICAL_CARD = 'PHYSICAL_CARD',
  POSTED = 'POSTED',
  AWAITING_ACTIVATION = 'AWAITING_ACTIVATION',
  CARD_LOST = 'CARD_LOST',
  CARD_SYSTEM_EXPIRED = 'CARD_SYSTEM_EXPIRED',
  CARD_EXPIRED = 'CARD_EXPIRED',
}
