export enum CardStatus {
  AWAITING_BATCHING = 'AWAITING_BATCHING',
  ADDED_TO_BATCH = 'ADDED_TO_BATCH',
  AWAITING_POSTAGE = 'AWAITING_POSTAGE',
  PHYSICAL_CARD = 'PHYSICAL_CARD',
  VIRTUAL_CARD = 'VIRTUAL_CARD',
  CARD_LOST = 'CARD_LOST',
  DISABLED = 'DISABLED',
  CARD_EXPIRED = 'CARD_EXPIRED',
}
