export enum RejectionReason {
  DECLINE_INCORRECT_ID = 'DECLINE_INCORRECT_ID',
  PICTURE_DECLINE_ID = 'PICTURE_DECLINE_ID',
  DL_PP_DECLINE_ID = 'DL_PP_DECLINE_ID',
  DATE_DECLINE_ID = 'DATE_DECLINE_ID',
  BLURRY_IMAGE_DECLINE_ID = 'BLURRY_IMAGE_DECLINE_ID',
  DIFFERENT_NAME_DECLINE_ID = 'DIFFERENT_NAME_DECLINE_ID',
  PASSWORD_PROTECTED_DECLINE_ID = 'PASSWORD_PROTECTED_DECLINE_ID',
  DECLINE_NOT_ELIGIBLE = 'DECLINE_NOT_ELIGIBLE',
}
