name: Auto-Remove Stale Resources

on:
  schedule: # Run every day at 00:00
    - cron: '0 0 * * *'
  workflow_dispatch: # Run manually

concurrency:
  group: auto-remove-stale-resources
  cancel-in-progress: true

jobs:
  remove-stale-stacks:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Non Prod AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::314658777488:role/github-actions-role
          aws-region: eu-west-2
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            scripts/removeStaleStacks.sh
      - name: Remove Stale Stacks
        run: |
          ./scripts/removeStaleStacks.sh
      - name: Upload intermediate results
        uses: actions/upload-artifact@v4
        with:
          name: intermediate-results
          path: "*.json"
