name: 'CMS Pages'
on:
  push:
    paths:
      - packages/cms-pages/**
      - scripts/**
      - packages/shared-ui/**
      - package-lock.json
      - package.json
      - .github/actions/**
      - .github/workflows/cms-pages.yml
  pull_request:
    paths:
      - packages/cms-pages/**
      - scripts/**
      - packages/shared-ui/**
      - package-lock.json
      - package.json
      - .github/actions/**
      - .github/workflows/cms-pages.yml

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          restore_cache: false
          token: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run Unit Tests
        run: npm run test:coverage -w packages/cms-pages

  lint:
    name: Linting
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: JavaScript and Typescript
        env:
          NEXT_PUBLIC_SANITY_PROJECT_ID: td1j6hke
          NEXT_PUBLIC_SANITY_DATASET_NAME: develop
        run: npm run lint -w packages/cms-pages

  storybook:
    name: Storybook Preview
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.storybook-publish.outputs.url }}
    needs:
      - install
      - test
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Publish
        uses: ./.github/actions/storybook
        id: storybook-publish
        with:
          cloudflareApiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflareAccountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          packageName: cms-pages
          brandDeployments: true
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build
    if: false
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build
        env:
          NEXT_PUBLIC_SANITY_PROJECT_ID: td1j6hke
          NEXT_PUBLIC_SANITY_DATASET_NAME: develop
        run: npm run build -w packages/cms-pages
