name: 'CMS Pages'
on:
  push:
    paths:
      - packages/cms-pages/**
      - scripts/**
      - package-lock.json
      - package.json
      - .github/actions/**
      - .github/workflows/cms-pages.yml
  pull_request:
    paths:
      - packages/cms-pages/**
      - scripts/**
      - package-lock.json
      - package.json
      - .github/actions/**
      - .github/workflows/cms-pages.yml

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          restore_cache: false
          token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    name: Linting
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: JavaScript and Typescript
        env:
          NEXT_PUBLIC_SANITY_PROJECT_ID: td1j6hke
          NEXT_PUBLIC_SANITY_DATASET_NAME: develop
        run: npm run lint -w packages/cms-pages

  build:
    name: Build
    if: false
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build
        env:
          NEXT_PUBLIC_SANITY_PROJECT_ID: td1j6hke
          NEXT_PUBLIC_SANITY_DATASET_NAME: develop
        run: npm run build -w packages/cms-pages
