name: Core
on:
  push:
    branches:
      - main
    paths:
      - packages/api/core/**
      - .github/workflows/core.yml
      - package-lock.json
      - package.json
  pull_request:
    paths:
      - packages/api/core/**
      - .github/workflows/core.yml
      - package-lock.json
      - package.json

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          restore_cache: false
          token: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
      - name: Generate SST Types
        env:
          BRAND: BLC_UK
        run: npx sst types --stage staging
      - name: Test
        run: npm run test:coverage -w packages/api/core
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        if: github.actor != 'dependabot[bot]'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectBaseDir: packages/api/core

  typecheck:
    name: Check Types
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Generate SST Types
        env:
          BRAND: BLC_UK
        run: npx sst types --stage staging
      - name: Check Types
        run: npm run typecheck -w packages/api/core
