name: 'Frontend Coverage'
on:
  pull_request_target:
    branches:
      - main
    paths:
      - packages/web/**
      - package-lock.json
      - .github/workflows/web.yml
      - .github/workflows/coverage.yml

permissions:
  contents: read # for checkout repository
  actions: read # for fetching base branch bundle stats
  pull-requests: write # for comments

jobs:
  coverage:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - uses: bahmutov/npm-install@v1
        - uses: ArtiomTr/jest-coverage-report-action@v2
          with:
            test-script: npm test
            working-directory: ./packages/web
