name: Destroy PR Environment

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]

env:
  PR_PREFIX: pr-${{ github.event.pull_request.number }}-blc-mono

permissions:
  id-token: write
  contents: read

jobs:
  remove:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Configure Non Prod AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::314658777488:role/github-actions-role
          aws-region: eu-west-2
      - name: Destroy Global
        run: npx sst remove --stage $PR_PREFIX
