name: 'Member-Services-Hub'
on:
  push:
    paths:
      - packages/member-services-hub/**
      - package-lock.json
      - sst.config.ts
      - package.json
      - .github/workflows/member-services-hub.yml
  pull_request:
    paths:
      - packages/member-services-hub/**
      - package-lock.json
      - sst.config.ts
      - package.json
      - .github/workflows/member-services-hub.yml

env:
  PKG_NAME: member-services-hub
  STORYBOOK_PROJECT_NAME: admin-panel-storybook
  STORYBOOK_BUILD_OUTPUT: storybook-static

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{hashFiles('package-lock.json')}}
          restore-keys: node_modules- # Take any latest cache if failed to find it for current yarn.lock
      - run: npm install
      - run: npm test -w packages/${{ env.PKG_NAME }}

  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{hashFiles('package-lock.json')}}
          restore-keys: node_modules- # Take any latest cache if failed to find it for current yarn.lock
      - run: npm install
      - name: JavaScript and Typescript
        run: npm run lint -w packages/${{ env.PKG_NAME }}
      - name: Styles
        run: npm run lint:style -w packages/${{ env.PKG_NAME }}
  
  storybook:
    name: Storybook Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{hashFiles('package-lock.json')}}
          restore-keys: node_modules- # Take any latest cache if failed to find it for current yarn.lock
      - run: npm install
      - name: Build
        run: npm run build-storybook -w packages/${{ env.PKG_NAME }}
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ env.STORYBOOK_PROJECT_NAME }}
          directory: packages/${{ env.PKG_NAME }}/${{ env.STORYBOOK_BUILD_OUTPUT }}
          branch: ${{ github.ref_name }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}