name: 'Mobile Hybrid'
on:
  push:
    paths:
      - packages/mobile-hybrid/**
      - package-lock.json
      - sst.config.ts
      - package.json
      - .github/workflows/mobile-hybrid.yml
  pull_request:
    paths:
      - packages/mobile-hybrid/**
      - package-lock.json
      - sst.config.ts
      - package.json
      - .github/workflows/mobile-hybrid.yml

env:
  PKG_NAME: mobile-hybrid
  STORYBOOK_PROJECT_NAME: mobile-hybrid-storybook
  STORYBOOK_BUILD_OUTPUT: storybook-static

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          restore_cache: false
          token: ${{ secrets.GITHUB_TOKEN }}

  dev-env-mapping:
    if: github.event_name == 'push' && github.ref != 'refs/heads/main'
    name: Dev env mapping
    runs-on: ubuntu-latest
    outputs:
      devEnv: ${{ steps.dev-env.outputs[github.actor] }}
    steps:
      - uses: actions/checkout@v4
      - id: dev-env
        run: echo $(grep "${{ github.actor }}=" packages/mobile-hybrid/dev-env-mapping.txt) >> "$GITHUB_OUTPUT"

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build shared-ui
        run: npm run build -w packages/shared-ui
      - name: Run Unit Tests
        run: npm test -w packages/mobile-hybrid

  lint:
    name: Linting
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build shared-ui
        run: npm run build -w packages/shared-ui
      - name: JavaScript and Typescript
        run: npm run lint -w packages/mobile-hybrid

  storybook:
    name: Storybook Preview
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.cloudflare-pages.outputs.url }}
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build shared-ui
        run: npm run build -w packages/shared-ui
      - name: Build
        run: npm run build-storybook -w packages/${{ env.PKG_NAME }}
      - name: Publish
        uses: cloudflare/pages-action@1
        id: cloudflare-pages
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ env.STORYBOOK_PROJECT_NAME }}
          directory: packages/${{ env.PKG_NAME }}/${{ env.STORYBOOK_BUILD_OUTPUT }}
          branch: ${{ github.ref_name }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

  comment:
    name: Comment on PR
    runs-on: ubuntu-latest
    needs:
      - storybook
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        if: success() && github.event.number
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          body-includes: '🚀 Successfully deployed storybook'

      - name: Create Comment
        uses: peter-evans/create-or-update-comment@v3
        if: success() && github.event.number
        with:
          issue-number: ${{ github.event.number }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
          body: |
            ## 🚀 Successfully deployed storybook

            <p><b>Storybook Url:</b> <a href="${{ needs.storybook.outputs.url }}">${{ needs.storybook.outputs.url }}</a></p>

  dev:
    if: github.event_name == 'push' && github.ref != 'refs/heads/main' && needs.dev-env-mapping.outputs.devEnv
    name: Deploy Dev
    runs-on: ubuntu-latest
    needs:
      - install
      - dev-env-mapping
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build shared-ui
        run: npm run build -w packages/shared-ui
      - name: Build
        run: npm run build -w packages/mobile-hybrid
      - name: Publishing env ${{ needs.dev-env-mapping.outputs.devEnv }}
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ needs.dev-env-mapping.outputs.devEnv }}
          branch: 'main'
          directory: packages/mobile-hybrid/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

  staging:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Deploy Staging
    runs-on: ubuntu-latest
    needs:
      - install
      - test
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build shared-ui
        run: npm run build -w packages/shared-ui
      - name: Build
        run: npm run build -w packages/mobile-hybrid
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'mobile-hybrid-poc'
          directory: packages/mobile-hybrid/dist
          branch: 'main'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Deploy Production
    environment: Production
    runs-on: ubuntu-latest
    needs:
      - install
      - test
      - staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build shared-ui
        run: npm run build -w packages/shared-ui
      - name: Build
        run: npm run build -w packages/mobile-hybrid
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'mobile-hybrid'
          directory: packages/mobile-hybrid/dist
          branch: 'main'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
