name: 'Mobile Hybrid'
on:
  push:
    paths:
      - packages/mobile-hybrid/**
      - packages/shared-ui/**
      - scripts/**
      - package-lock.json
      - sst.config.ts
      - package.json
      - .github/actions/**
      - .github/workflows/mobile-hybrid.yml
  pull_request:
    paths:
      - packages/mobile-hybrid/**
      - packages/shared-ui/**
      - scripts/**
      - package-lock.json
      - sst.config.ts
      - package.json
      - .github/actions/**
      - .github/workflows/mobile-hybrid.yml

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          restore_cache: false
          token: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run Unit Tests
        run: npm test -w packages/mobile-hybrid

  lint:
    name: Linting
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: JavaScript and Typescript
        run: npm run lint -w packages/mobile-hybrid

  typecheck:
    name: Check Types
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Check Types
        run: npm run typecheck -w packages/mobile-hybrid

  storybook:
    name: Storybook Preview
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.storybook-publish.outputs.url }}
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Publish
        uses: ./.github/actions/storybook
        id: storybook-publish
        with:
          cloudflareApiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflareAccountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          packageName: mobile-hybrid
          brandDeployments: true
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

  changelog:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Changelog
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.tag-release.outputs.releases_created }}
    steps:
      - uses: googleapis/release-please-action@v3
        id: tag-release
        with:
          path: packages/mobile-hybrid
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          monorepo-tags: true
          package-name: bluelightcard/mobile-hybrid
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Other Changes","hidden":false},{"type":"refactor","section":"Other Changes","hidden":false}]'

  staging:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Deploy Staging
    environment: Staging
    strategy:
      matrix:
        include:
          - brand: 'blc-uk-current'
            cloudflare_pages_name: 'mobile-hybrid-poc'
            branch: 'main'
          - brand: 'blc-uk'
            cloudflare_pages_name: 'mobile-hybrid-blc-uk'
            branch: 'staging'
          - brand: 'blc-au'
            cloudflare_pages_name: 'mobile-hybrid-blc-au'
            branch: 'staging'
          - brand: 'dds-uk'
            cloudflare_pages_name: 'mobile-hybrid-dds'
            branch: 'staging'
    runs-on: ubuntu-latest
    needs:
      - install
      - test
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build
        run: NEXT_PUBLIC_APP_BRAND=${{matrix.brand}} NEXT_PUBLIC_BRAND_URL=${{matrix.brand_url}} npm run build -w packages/mobile-hybrid
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ matrix.cloudflare_pages_name }}
          directory: packages/mobile-hybrid/dist
          branch: ${{ matrix.branch }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.changelog.outputs.releases_created
    name: Deploy Production
    environment: Production
    strategy:
      matrix:
        include:
          - brand: 'blc-uk-current'
            cloudflare_pages_name: 'mobile-hybrid'
          - brand: 'blc-uk'
            cloudflare_pages_name: 'mobile-hybrid-blc-uk'
          - brand: 'blc-au'
            cloudflare_pages_name: 'mobile-hybrid-blc-au'
          - brand: 'dds-uk'
            cloudflare_pages_name: 'mobile-hybrid-dds'
    runs-on: ubuntu-latest
    needs:
      - install
      - test
      - changelog
      - staging
    env:
      NEXT_PUBLIC_APP_BRAND: ${{matrix.brand}}
      NEXT_PUBLIC_BRAND_URL: bluelightcard.co.uk
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build
        run: NEXT_PUBLIC_APP_BRAND=${{matrix.brand}} NEXT_PUBLIC_BRAND_URL=bluelightcard.co.uk npm run build -w packages/mobile-hybrid
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ matrix.cloudflare_pages_name }}
          directory: packages/mobile-hybrid/dist
          branch: 'main'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
