name: Offers
on:
  push:
    branches:
      - main
    paths:
      - packages/shared/**
      - packages/api/offers/**
      - packages/api/offers-cms/**
      - packages/api/core/**
      - stacks/**
      - .github/workflows/offers.yml
      - package-lock.json
      - sst.config.ts
      - package.json
  pull_request:
    paths:
      - packages/shared/**
      - packages/api/offers/**
      - packages/api/offers-cms/**
      - packages/api/core/**
      - stacks/**
      - .github/workflows/offers.yml
      - package-lock.json
      - sst.config.ts
      - package.json

permissions: write-all

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          restore_cache: false
          token: ${{ secrets.GITHUB_TOKEN }}
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run Tests
        run: npm run test:coverage -w packages/api/offers
#      - name: SonarQube Scan
#        uses: SonarSource/sonarqube-scan-action@master
#        if: github.actor != 'dependabot[bot]'
#        env:
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          projectBaseDir: packages/api/offers

  changelog:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Changelog
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.tag-release.outputs.releases_created }}
    steps:
      - uses: googleapis/release-please-action@v3
        id: tag-release
        with:
          path: packages/api/offers
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          monorepo-tags: true
          package-name: bluelightcard/offers
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Other Changes","hidden":false},{"type":"refactor","section":"Other Changes","hidden":false}]'

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - install
      - test
      - changelog
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build
        run: npm run build

  staging:
    name: Staging Deployment
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - deployment: 'blc-uk-staging'
            region: 'eu-west-2'
            stagingBaseUrl: https://staging.bluelightcard.co.uk
            legacyApiRetrieveOffersEndpoint: api/4/offer/retrieve.php
            offersHomepageMenuBrandPrefix: blc-uk
            cdnUrl: 'https://blcimgdev.s3.eu-west-2.amazonaws.com'
            brand: BLC_UK
            stage: staging
            discoveryEventBusName: 'staging-blc-mono-eventBus'
            cmsAccount: '971422711515'
            userProfileEndpoint: https://staging-identity.blcshine.io/user
            companyLocationDwhStream: 'staging-dwh-blc-uk-company-location'
            menuDwhStream: 'staging-dwh-blc-uk-menu'
            themedMenuDwhStream: 'staging-dwh-blc-uk-themed-menu'
          - deployment: 'dds-uk-staging'
            region: 'eu-west-2'
            stagingBaseUrl: https://www.ddsstaging.bluelightcard.tech
            legacyApiRetrieveOffersEndpoint: api/4/offer/retrieve.php
            offersHomepageMenuBrandPrefix: dds-uk
            cdnUrl: 'https://ddsimgdev.s3.eu-west-2.amazonaws.com'
            brand: DDS_UK
            stage: staging-dds
            cmsAccount: '971422711515'
            discoveryEventBusName: 'staging-dds-blc-mono-eventBus'
            blcUkCognitoUserPoolId: 'eu-west-2_Ow2L8azIb'
            blcUkOldCognitoUserPoolId: 'eu-west-2_rNmQEiFS4'
            ddsCognitoUserPoolId: 'eu-west-2_VdsvVVUrI'
            ddsOldCognitoUserPoolId: 'eu-west-2_jbLX0JEdN'
            blcUkIdentityApiId: 'tr1afrar24'
            userProfileEndpoint: https://staging-identity.blcshine.io/user
            companyLocationDwhStream: 'staging-dds-dwh-dds-uk-company-location'
            menuDwhStream: 'staging-dds-dwh-dds-uk-menu'
            themedMenuDwhStream: 'staging-dds-dwh-dds-uk-themed-menu'
          - deployment: 'blc-aus-staging'
            region: 'ap-southeast-2'
            cmsAccount: '971422711515'
            stagingBaseUrl: https://www.develop.bluelightcard.com.au
            legacyApiRetrieveOffersEndpoint: api/4/offer/retrieve.php
            offersHomepageMenuBrandPrefix: blc-aus
            cdnUrl: 'https://blc-au-img-dev.s3.ap-southeast-2.amazonaws.com'
            brand: BLC_AU
            stage: staging
            discoveryEventBusName: 'staging-blc-mono-eventBus'
            userProfileEndpoint: https://staging-identity-au.blcshine.io/user
            companyLocationDwhStream: 'staging-dwh-blc-au-company-location'
            menuDwhStream: 'staging-dwh-blc-au-menu'
            themedMenuDwhStream: 'staging-dwh-blc-au-themed-menu'
    needs:
      - install
      - test
      - build
      - changelog
    env:
      STAGING_BASE_URL: ${{matrix.stagingBaseUrl}}
      LEGACY_API_RETRIEVE_OFFERS_ENDPOINT: ${{matrix.legacyApiRetrieveOffersEndpoint}}
      OFFERS_HOMEPAGE_MENU_BRAND_PREFIX: ${{matrix.offersHomepageMenuBrandPrefix}}
      CDN_URL: ${{matrix.cdnUrl}}
      BRAND: ${{matrix.brand}}
      BLC_UK_COGNITO_USER_POOL_ID: ${{ matrix.blcUkCognitoUserPoolId }}
      BLC_UK_OLD_COGNITO_USER_POOL_ID: ${{ matrix.blcUkOldCognitoUserPoolId }}
      DDS_COGNITO_USER_POOL_ID: ${{ matrix.ddsCognitoUserPoolId }}
      DDS_OLD_COGNITO_USER_POOL_ID: ${{ matrix.ddsOldCognitoUserPoolId }}
      BLC_UK_IDENTITY_API_ID: ${{ matrix.blcUkIdentityApiId }}
      OFFERS_DISCOVERY_EVENT_BUS_NAME: ${{ matrix.discoveryEventBusName }}
      OFFERS_CMS_ACCOUNT: ${{ matrix.cmsAccount }}
      USER_PROFILE_ENDPOINT: ${{ matrix.userProfileEndpoint }}
      DWH_FIREHOSE_COMPANY_LOCATION_STREAM_NAME: ${{ matrix.companyLocationDwhStream }}
      DWH_FIREHOSE_MENU_STREAM_NAME: ${{ matrix.menuDwhStream }}
      DWH_FIREHOSE_THEMED_MENU_STREAM_NAME: ${{ matrix.themedMenuDwhStream }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Configure Non Prod AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::314658777488:role/github-actions-role
          aws-region: ${{matrix.region}}
      - name: Build
        run: npm run build
      - name: Get Service Tags
        run: |
          echo "DD_VERSION=$(date +%m-%d-%Y)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "DD_ENV=staging" >> $GITHUB_ENV
          echo "DD_GIT_COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "DD_GIT_REPOSITORY_URL=https://github.com/${{ github.repository }}" >> $GITHUB_ENV
      - name: Deploy Stack
        env:
          DD_VERSION: '${{ env.DD_VERSION }}'
          DD_ENV: '${{ env.DD_ENV }}'
          DD_GIT_COMMIT_SHA: '${{ env.DD_GIT_COMMIT_SHA }}'
          DD_GIT_REPOSITORY_URL: '${{ env.DD_GIT_REPOSITORY_URL }}'
          DD_API_KEY: '${{ secrets.DATADOG_AWS_INSTRUMENTATION_TOKEN }}'
          USE_DATADOG_AGENT: 'true'
        run: npx sst deploy global --stage ${{matrix.stage}} --region ${{matrix.region}} && npx sst deploy offers --stage ${{matrix.stage}} --region ${{matrix.region}}
      - name: Datadog deployment metrics
        uses: ./.github/actions/datadog
        with:
          environment: 'staging'
          service_name: 'offers'
          workflow_run_id: ${{ github.run_id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DATADOG_DORA_METRICS_CLIENT_TOKEN: ${{ secrets.DATADOG_DORA_METRICS_CLIENT_TOKEN }}
      - name: Send Slack message on failure
        if: ${{ failure() }}
        uses: bluelightcard/github-actions-slack-notification@v1
        with:
          webhook_url: ${{ secrets.CI_FAILURE_NOTIFICATIONS_WEBHOOK }}
          title: ':x: :test_tube: Staging deployment failed for Offers (${{matrix.brand}})!'
      - name: Send Slack message on success
        if: ${{ success() }}
        uses: bluelightcard/github-actions-slack-notification@v1
        with:
          webhook_url: ${{ secrets.CI_SUCCESS_NOTIFICATIONS_WEBHOOK }}
          title: ':white_check_mark: :test_tube: Staging deployment for Offers (${{matrix.brand}}) was successful!'

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.changelog.outputs.releases_created
    needs:
      - install
      - test
      - staging
      - changelog
      - build
    uses: ./.github/workflows/production-deploy-offers.yml
    secrets: inherit
