name: Playwright UK Login Test

on:
  schedule:
    - cron: '*/10 * * * *' # Run every 10 minutes
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout repo and install dependencies
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Install dependencies
        working-directory: packages/web-playwright-tests
        run: npm install

      # Install Playwright
      - name: Install Playwright
        working-directory: packages/web-playwright-tests
        run: npx playwright install

      # Run specified Playwright test with retry logic
      - name: Run Playwright test - Login to UK
        working-directory: packages/web-playwright-tests
        id: playwright
        run: |
          for i in {1..2}; do
            if npx playwright test -g "@Uk @Smoke @Web @NeedsTestCase - Login to uk home page"; then
              echo "Test passed on attempt $i."
              break
            fi
            if [ $i -lt 2 ]; then
              echo "Test failed, retrying... ($i/2)"
            else
              echo "Test failed after 2 re-run attempts."
              exit 1
            fi
          done

      # Upload Playwright report if the test fails
      - name: Upload Playwright report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: packages/web-playwright-tests/html-report

      # Send Slack message if all retries fail
      - name: Send Slack message on fail
        if: failure()
        run: |
          WORKFLOW_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "*Playwright Web test `Login to UK home page` has failed after 3 attempts against production - Login may not be functioning correctly. Check the [workflow run report]('"$WORKFLOW_URL"') for further details.*",
            "mrkdwn": true
          }' ${{ vars.CI_NOTIFICATIONS_WEBHOOK }}
