name: Deploy Offers to Production

on:
  workflow_call:
    inputs:
      commit_hash_or_tag:
        description: The commit SHA that you wish to revert to
        type: string
        default: 'main'

jobs:
  release-offers-to-production:
    name: Release to production
    environment: Production
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - namespace: 'blc-uk-production'
            region: 'eu-west-2'
            prodBaseUrl: https://www.bluelightcard.co.uk
            legacyApiRetrieveOffersEndpoint: api/4/offer/retrieve.php
            offersHomepageMenuBrandPrefix: blc-uk
            cdnUrl: 'https://cdn.bluelightcard.co.uk'
            brand: BLC_UK
            stage: production
            discoveryEventBusName: 'production-blc-mono-eventBus'
            cmsAccount: '084375547292'
            userProfileEndpoint: https://identity.blcshine.io/user
            companyLocationDwhStream: 'production-dwh-blc-uk-company-location'
          - deployment: 'dds-uk-production'
            region: 'eu-west-2'
            prodBaseUrl: https://www.defencediscountservice.co.uk
            legacyApiRetrieveOffersEndpoint: api/4/offer/retrieve.php
            offersHomepageMenuBrandPrefix: dds-uk
            cdnUrl: 'https://cdn.defencediscountservice.co.uk'
            brand: DDS_UK
            stage: production-dds
            discoveryEventBusName: 'production-dds-blc-mono-eventBus'
            cmsAccount: '084375547292'
            blcUkCognitoUserPoolId: 'eu-west-2_D3aAVuWHo'
            blcUkOldCognitoUserPoolId: 'eu-west-2_jrwTfFRgM'
            ddsCognitoUserPoolId: 'eu-west-2_3WlS5ZkAh'
            ddsOldCognitoUserPoolId: 'eu-west-2_y2KyCUbVT'
            blcUkIdentityApiId: 'ue8dcieh75'
            userProfileEndpoint: https://identity.blcshine.io/user
            companyLocationDwhStream: 'production-dds-dwh-dds-uk-company-location'
          - namespace: 'blc-aus-production'
            region: 'ap-southeast-2'
            prodBaseUrl: https://www.bluelightcard.com.au
            legacyApiRetrieveOffersEndpoint: api/4/offer/retrieve.php
            offersHomepageMenuBrandPrefix: blc-aus
            cdnUrl: 'https://cdn.bluelightcard.com.au'
            brand: BLC_AU
            stage: production
            discoveryEventBusName: 'production-blc-mono-eventBus'
            cmsAccount: '084375547292'
            userProfileEndpoint: https://identity-au.blcshine.io/user
            companyLocationDwhStream: 'production-dwh-blc-au-company-location'
    env:
      PROD_BASE_URL: ${{matrix.prodBaseUrl}}
      LEGACY_API_RETRIEVE_OFFERS_ENDPOINT: ${{matrix.legacyApiRetrieveOffersEndpoint}}
      OFFERS_HOMEPAGE_MENU_BRAND_PREFIX: ${{matrix.offersHomepageMenuBrandPrefix}}
      CDN_URL: ${{matrix.cdnUrl}}
      BRAND: ${{matrix.brand}}
      BLC_UK_COGNITO_USER_POOL_ID: ${{ matrix.blcUkCognitoUserPoolId }}
      BLC_UK_OLD_COGNITO_USER_POOL_ID: ${{ matrix.blcUkOldCognitoUserPoolId }}
      DDS_COGNITO_USER_POOL_ID: ${{ matrix.ddsCognitoUserPoolId }}
      DDS_OLD_COGNITO_USER_POOL_ID: ${{ matrix.ddsOldCognitoUserPoolId }}
      BLC_UK_IDENTITY_API_ID: ${{ matrix.blcUkIdentityApiId }}
      USER_PROFILE_ENDPOINT: ${{ matrix.userProfileEndpoint }}
      OFFERS_DISCOVERY_EVENT_BUS_NAME: ${{ matrix.discoveryEventBusName }}
      OFFERS_CMS_ACCOUNT: ${{ matrix.cmsAccount }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit_hash_or_tag }}
      - name: Setup
        uses: ./.github/actions/setup
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure Prod AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{matrix.region}}
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_PROD }}
      - name: Build
        run: npm run build
      - name: Get Service Tags
        run: |
          echo "DD_VERSION=$(date +%m-%d-%Y)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "DD_ENV=production" >> $GITHUB_ENV
          echo "DD_GIT_COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "DD_GIT_REPOSITORY_URL=https://github.com/${{ github.repository }}" >> $GITHUB_ENV
      - name: Deploy Stack
        env:
          DD_VERSION: '${{ env.DD_VERSION }}'
          DD_ENV: '${{ env.DD_ENV }}'
          DD_GIT_COMMIT_SHA: '${{ env.DD_GIT_COMMIT_SHA }}'
          DD_GIT_REPOSITORY_URL: '${{ env.DD_GIT_REPOSITORY_URL }}'
          DD_API_KEY: '${{ secrets.DATADOG_AWS_INSTRUMENTATION_TOKEN }}'
          USE_DATADOG_AGENT: 'true'
        run: npx sst deploy global --stage ${{matrix.stage}} --region ${{matrix.region}} && npx sst deploy offers --stage ${{matrix.stage}} --region ${{matrix.region}}
      - name: Datadog deployment metrics
        uses: ./.github/actions/datadog
        with:
          environment: 'production'
          service_name: 'offers'
          workflow_run_id: ${{ github.run_id }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DATADOG_DORA_METRICS_CLIENT_TOKEN: ${{ secrets.DATADOG_DORA_METRICS_CLIENT_TOKEN }}
      - name: Send Slack message on failure
        if: ${{ failure() }}
        uses: bluelightcard/github-actions-slack-notification@v1
        with:
          webhook_url: ${{ secrets.CI_FAILURE_NOTIFICATIONS_WEBHOOK }}
          title: ':x: Production deployment failed for Offers (${{matrix.brand}})!'
      - name: Send Slack message on success
        if: ${{ success() }}
        uses: bluelightcard/github-actions-slack-notification@v1
        with:
          webhook_url: ${{ secrets.CI_SUCCESS_NOTIFICATIONS_WEBHOOK }}
          title: ':white_check_mark: Production deployment for Offers (${{matrix.brand}}) was successful!'
