name: Deploy Member Services Hub to Production

on:
  workflow_call:
    inputs:
      commit_hash_or_tag:
        description: The commit SHA that you wish to revert to
        type: string
        default: 'main'

jobs:
  release-member-services-hub:
    name: Deploy Member Services Hub to Production
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit_hash_or_tag }}
      - name: Setup
        uses: ./.github/actions/setup
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: npm run build -w packages/${{ env.PKG_NAME }}
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ env.PKG_NAME }}
          branch: 'main'
          directory: packages/${{ env.PKG_NAME }}/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
