name: Deploy Mobile Hybrid to Production

on:
  workflow_call:
    inputs:
      commit_hash_or_tag:
        description: The commit SHA that you wish to revert to
        type: string
        default: 'main'

jobs:
  release-mobile-hybrid:
    name: Deploy Production
    environment: Production
    strategy:
      matrix:
        include:
          - brand: 'blc-uk-current'
            brand_url: 'bluelightcard.co.uk'
            cloudflare_pages_name: 'mobile-hybrid'
            fsiCompanyIds: '38142, 41155, 41286'
          - brand: 'blc-uk'
            brand_url: 'bluelightcard.co.uk'
            cloudflare_pages_name: 'mobile-hybrid-blc-uk'
            fsiCompanyIds: '38142, 41155, 41286'
          - brand: 'blc-au'
            brand_url: 'bluelightcard.com.au'
            cloudflare_pages_name: 'mobile-hybrid-blc-au'
            fsiCompanyIds: ''
          - brand: 'dds-uk'
            brand_url: 'defencediscountservice.co.uk'
            cloudflare_pages_name: 'mobile-hybrid-dds'
            fsiCompanyIds: ''
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_APP_BRAND: ${{ matrix.brand }}
      NEXT_PUBLIC_BRAND_URL: ${{matrix.brand_url}}
      NEXT_PUBLIC_FSI_COMPANY_IDS: ${{matrix.fsiCompanyIds}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit_hash_or_tag }}
      - name: Setup
        uses: ./.github/actions/setup
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate SST Types
        env:
          BRAND: BLC_UK
        run: npx sst types --stage production
      - name: Build
        run: npm run build -w packages/mobile-hybrid
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ matrix.cloudflare_pages_name }}
          directory: packages/mobile-hybrid/dist
          branch: 'main'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Send Slack message on failure
        if: ${{ failure() }}
        uses: bluelightcard/github-actions-slack-notification@v1
        with:
          webhook_url: ${{ secrets.CI_FAILURE_NOTIFICATIONS_WEBHOOK }}
          title: '@here :x: Production deployment failed for Mobile Hybrid (${{matrix.brand}})!'
      - name: Send Slack message on success
        if: ${{ success() }}
        uses: bluelightcard/github-actions-slack-notification@v1
        with:
          webhook_url: ${{ secrets.CI_SUCCESS_NOTIFICATIONS_WEBHOOK }}
          title: ':rocket: Production deployment for Mobile Hybrid (${{matrix.brand}}) was successful!'
