name: Shared UI
on:
  push:
    branches:
      - main
    paths:
      - packages/shared-ui/**
      - .github/workflows/shared-ui.yml
      - package-lock.json
      - package.json
  pull_request:
    paths:
      - packages/shared-ui/**
      - .github/workflows/shared-ui.yml
      - package-lock.json
      - package.json

env:
  PKG_NAME: shared-ui

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          restore_cache: false
          token: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup
        uses: ./.github/actions/setup
      - run: npm run test:coverage -w packages/shared-ui
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        if: github.actor != 'dependabot[bot]'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectBaseDir: packages/shared-ui


  lint:
    name: Linting
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup
        uses: ./.github/actions/setup
      - run: npm run lint -w packages/shared-ui

  typecheck:
    name: Check Types
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Generate SST Types
        env:
          BRAND: BLC_UK
        run: npx sst types --stage staging
      - name: Check Types
        run: npm run typecheck -w packages/shared-ui

  storybook:
    name: Storybook Preview
    runs-on: ubuntu-latest
    needs: install
    outputs:
      url: ${{ steps.storybook-publish.outputs.url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup
        uses: ./.github/actions/setup
      - name: Publish
        uses: ./.github/actions/storybook
        id: storybook-publish
        with:
          cloudflareApiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflareAccountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          packageName: ${{ env.PKG_NAME }}
          brandDeployments: true
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
