name: 'Web'
on:
  push:
    branches:
      - main
    paths:
      - packages/web/**
      - package-lock.json
      - sst.config.ts
      - package.json
      - .github/workflows/web.yml
  pull_request:
    paths:
      - packages/web/**
      - package-lock.json
      - sst.config.ts
      - package.json
      - .github/workflows/web.yml

env:
  CI: true

permissions: write-all

jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          restore_cache: false
          token: ${{ secrets.GITHUB_TOKEN }}

  changes:
    name: Changes
    runs-on: ubuntu-latest
    outputs:
      components: ${{ steps.filter.outputs.components }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            components:
              - 'packages/web/src/common/components/**'
              - 'packages/web/src/offers/components/**'

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: install
    env:
      NEXT_PUBLIC_COGNITO_CLIENT_REGION: eu-west-2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build shared-ui
        run: npm run build -w packages/shared-ui
      - name: Run Unit Tests
        run: npm test -w packages/web

  lint:
    name: Linting
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: JavaScript and Typescript
        run: npm run lint -w packages/web

  lint-styles:
    name: Linting Styles
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Lint Styles
        run: npm run lint:style -w packages/web

  storybook:
    if: github.event_name == 'pull_request' && needs.changes.outputs.components == 'true'
    name: Storybook Preview
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.cloudflare-pages.outputs.url }}
    needs:
      - install
      - changes
      - test
      - lint
      - lint-styles
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build shared-ui
        run: npm run build -w packages/shared-ui
      - name: Build
        run: npm run build-storybook -w packages/web
      - name: Publish
        uses: cloudflare/pages-action@1
        id: cloudflare-pages
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: web-storybook
          directory: packages/web/storybook-static
          branch: ${{ github.ref_name }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

  comment:
    name: Comment on PR
    runs-on: ubuntu-latest
    needs:
      - storybook
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        if: success() && github.event.number
        id: fc
        with:
          issue-number: ${{ github.event.number }}
          body-includes: '🚀 Successfully deployed storybook'

      - name: Create Comment
        uses: peter-evans/create-or-update-comment@v3
        if: success() && github.event.number
        with:
          issue-number: ${{ github.event.number }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
          body: |
            ## 🚀 Successfully deployed storybook

            <p><b>Storybook Url:</b> <a href="${{ needs.storybook.outputs.url }}">${{ needs.storybook.outputs.url }}</a></p>

  changelog:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Changelog
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.tag-release.outputs.releases_created }}
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v3
        id: tag-release
        with:
          path: packages/web
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          monorepo-tags: true
          package-name: bluelightcard/web
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Other Changes","hidden":false},{"type":"refactor","section":"Other Changes","hidden":false}]'

  staging:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Deploy Staging
    environment: Staging
    strategy:
      matrix:
        include:
          - brand: 'blc-uk'
            identity_brand: 'blc_uk'
            identity_api_key: 'IDENTITY_EU_WEST_2_API_KEY'
            datadog_app_id: 'DATADOG_BLC_UK_APP_ID'
            datadog_client_token: 'DATADOG_BLC_UK_CLIENT_TOKEN'
            datadog_default_service: 'web'
            region: 'eu-west-2'
            cognito_client_id: 'BLC_UK_COGNITO_CLIENT_ID'
            cognito_client_secret: 'BLC_UK_COGNITO_CLIENT_SECRET'
            redemption_details_endpoint: 'https://staging-redemptions.blcshine.io/member/redemptionDetails'
            redeem_endpoint: 'https://staging-redemptions.blcshine.io/member/redeem'
          - brand: 'blc-au'
            identity_brand: 'blc_au'
            identity_api_key: 'IDENTITY_AP_SOUTHEAST_2_API_KEY'
            cognito_client_id: 'BLC_AU_COGNITO_CLIENT_ID'
            cognito_client_secret: 'BLC_AU_COGNITO_CLIENT_SECRET'
            region: 'ap-southeast-2'
            # TODO(TR-391): Add appropriate endpoints once we have a redemptions staging deployment for BLC Australia
            redemption_details_endpoint: 'TODO'
            redeem_endpoint: 'TODO'
          - brand: 'dds-uk'
            identity_brand: 'dds_uk'
            identity_api_key: 'IDENTITY_EU_WEST_2_API_KEY'
            region: 'eu-west-2'
            cognito_client_id: 'DDS_UK_COGNITO_CLIENT_ID'
            cognito_client_secret: 'DDS_UK_COGNITO_CLIENT_SECRET'
            redemption_details_endpoint: 'https://staging-redemptions.blcshine.io/member/redemptionDetails'
            redeem_endpoint: 'https://staging-redemptions.blcshine.io/member/redeem'
    runs-on: ubuntu-latest
    needs:
      - install
      - test
      - lint
      - lint-styles
      - changelog
    env:
      NEXT_PUBLIC_AMPLITUDE_API_KEY: ${{ secrets.AMPLITUDE_API_KEY }}
      NEXT_PUBLIC_AMPLITUDE_DEPLOYMENT_KEY: ${{ secrets.AMPLITUDE_DEPLOYMENT_KEY }}
      NEXT_PUBLIC_OFFERS_ENDPOINT: https://w6cu72lyfngylgfvgjla66levi.appsync-api.eu-west-2.amazonaws.com/graphql
      NEXT_PUBLIC_OFFERS_API_GATEWAY_ENDPOINT: https://staging-offers.blcshine.io
      NEXT_PUBLIC_BLACK_FRIDAY_TIME_LOCK_START_DATE: '2023-11-14T01:00:00'
      NEXT_PUBLIC_BLACK_FRIDAY_TIME_LOCK_END_DATE: '2023-11-27T23:59:59'
      NEXT_PUBLIC_IDENTITY_API_URL: https://staging-identity.blcshine.io
      NEXT_PUBLIC_IDENTITY_API_KEY: ${{ secrets[matrix.identity_api_key] }}
      NEXT_PUBLIC_USER_PROFILE_ENDPOINT: /user
      NEXT_PUBLIC_ORGANISATION_ENDPOINT: /${{matrix.identity_brand}}/organisation
      NEXT_PUBLIC_ELIGIBILITY_FORM_OUTPUT_ENDPOINT: /${{matrix.identity_brand}}/formOutputData
      NEXT_PUBLIC_DATADOG_APP_ID: ${{ secrets[matrix.datadog_app_id] }}
      NEXT_PUBLIC_DATADOG_CLIENT_TOKEN: ${{ secrets[matrix.datadog_client_token] }}
      NEXT_PUBLIC_DATADOG_DEFAULT_SERVICE: ${{ matrix.datadog_default_service }}
      NEXT_PUBLIC_DATADOG_ENV: staging_stage
      NEXT_PUBLIC_SEARCH_ENDPOINT: https://lcsn8cd6i6.execute-api.eu-west-2.amazonaws.com/develop
      NEXT_PUBLIC_RETRIEVE_FAVOURITE_ENDPOINT: https://hmkt7fpodd.execute-api.eu-west-2.amazonaws.com/develop/Favourites/retrieve
      NEXT_PUBLIC_UPDATE_FAVOURITE_ENDPOINT: https://hmkt7fpodd.execute-api.eu-west-2.amazonaws.com/develop/Favourites/update
      NEXT_PUBLIC_RETRIEVE_OFFER_ENDPOINT: https://6sz52oo9ud.execute-api.eu-west-2.amazonaws.com/v1/offers/
      NEXT_PUBLIC_APP_MICROSERVICE_BRAND: BLC
      NEXT_PUBLIC_COGNITO_CLIENT_REGION: ${{matrix.region}}
      NEXT_PUBLIC_COGNITO_CLIENT_ID: ${{ secrets[matrix.cognito_client_id] }}
      NEXT_PUBLIC_COGNITO_CLIENT_SECRET: ${{ secrets[matrix.cognito_client_secret] }}
      NEXT_PUBLIC_FLAGSMITH_KEY: ${{ secrets.FLAGSMITH_KEY }}
      NEXT_PUBLIC_COGNITO_LOGIN_URL: https://staging-auth.blcshine.io/login?client_id=fk2gc4sadrmoqi91voamd6snu&response_type=code&scope=aws.cognito.signin.user.admin+email+openid+profile&redirect_uri=https%3A%2F%2Fwww.staging.bluelightcard.co.uk%2Fauth%2Fcallback.php
      NEXT_PUBLIC_COGNITO_LOGOUT_URL: https://staging-auth.blcshine.io/logout?client_id=fk2gc4sadrmoqi91voamd6snu&response_type=code&scope=aws.cognito.signin.user.admin+email+openid+profile&redirect_uri=https%3A%2F%2Fwww.staging.bluelightcard.co.uk%2Fauth%2Fcallback.php&logout_uri=https%3A%2F%2Fwww.staging.bluelightcard.co.uk%2Flogout.php
      NEXT_PUBLIC_REDEMPTION_DETAILS_ENDPOINT: ${{ matrix.redemption_details_endpoint }}
      NEXT_PUBLIC_REDEEM_ENDPOINT: ${{ matrix.redeem_endpoint }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build shared-ui
        run: npm run build -w packages/shared-ui
      - name: remove mock login
        run: rm -rf packages/web/src/pages/mock-login.tsx
      - name: Build
        run: NEXT_PUBLIC_APP_BRAND=${{matrix.brand}} npm run build -w packages/web
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{matrix.brand}}
          directory: packages/web/out
          branch: 'staging'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.changelog.outputs.releases_created
    name: Deploy Production
    strategy:
      matrix:
        include:
          - brand: 'blc-uk'
            identity_brand: 'blc_uk'
            identity_api_key: 'IDENTITY_EU_WEST_2_API_KEY'
            region: 'eu-west-2'
            cognito_client_id: 'BLC_UK_COGNITO_CLIENT_ID'
            cognito_client_secret: 'BLC_UK_COGNITO_CLIENT_SECRET'
            redemption_details_endpoint: 'https://redemptions.blcshine.io/member/redemptionDetails'
            redeem_endpoint: 'https://redemptions.blcshine.io/member/redeem'
          - brand: 'blc-au'
            identity_brand: 'blc_au'
            identity_api_key: 'IDENTITY_AP_SOUTHEAST_2_API_KEY'
            region: 'ap-southeast-2'
            cognito_client_id: 'BLC_AU_COGNITO_CLIENT_ID'
            cognito_client_secret: 'BLC_AU_COGNITO_CLIENT_SECRET'
            redemption_details_endpoint: 'https://o0xv8r20og.execute-api.ap-southeast-2.amazonaws.com/v1/member/redemptionDetails'
            redeem_endpoint: 'https://o0xv8r20og.execute-api.ap-southeast-2.amazonaws.com/v1/member/redeem'
          - brand: 'dds-uk'
            identity_brand: 'dds_uk'
            identity_api_key: 'IDENTITY_EU_WEST_2_API_KEY'
            region: 'eu-west-2'
            cognito_client_id: 'DDS_UK_COGNITO_CLIENT_ID'
            cognito_client_secret: 'DDS_UK_COGNITO_CLIENT_SECRET'
            redemption_details_endpoint: 'https://redemptions.blcshine.io/member/redemptionDetails'
            redeem_endpoint: 'https://redemptions.blcshine.io/member/redeem'
    environment: Production
    runs-on: ubuntu-latest
    needs:
      - install
      - test
      - lint
      - lint-styles
      - changelog
      - staging
    env:
      NEXT_PUBLIC_AMPLITUDE_API_KEY: ${{ secrets.AMPLITUDE_API_KEY }}
      NEXT_PUBLIC_AMPLITUDE_DEPLOYMENT_KEY: ${{ secrets.AMPLITUDE_DEPLOYMENT_KEY }}
      NEXT_PUBLIC_OFFERS_ENDPOINT: https://27d2m22mtvac5cvilrvb7kviyi.appsync-api.eu-west-2.amazonaws.com/graphql
      NEXT_PUBLIC_OFFERS_API_GATEWAY_ENDPOINT: https://offers.blcshine.io/
      NEXT_PUBLIC_BLACK_FRIDAY_TIME_LOCK_START_DATE: '2023-11-24T01:00:00'
      NEXT_PUBLIC_BLACK_FRIDAY_TIME_LOCK_END_DATE: '2023-11-27T23:59:59'
      NEXT_PUBLIC_IDENTITY_API_URL: https://identity.blcshine.io
      NEXT_PUBLIC_IDENTITY_API_KEY: ${{ secrets[matrix.identity_api_key] }}
      NEXT_PUBLIC_USER_PROFILE_ENDPOINT: /user
      NEXT_PUBLIC_ORGANISATION_ENDPOINT: /${{matrix.identity_brand}}/organisation
      NEXT_PUBLIC_ELIGIBILITY_FORM_OUTPUT_ENDPOINT: /${{matrix.identity_brand}}/formOutputData
      NEXT_PUBLIC_SEARCH_ENDPOINT: https://x26st9km9b.execute-api.eu-west-2.amazonaws.com/production
      NEXT_PUBLIC_RETRIEVE_FAVOURITE_ENDPOINT: https://ysgt36ldck.execute-api.eu-west-2.amazonaws.com/production/Favourites/retrieve
      NEXT_PUBLIC_UPDATE_FAVOURITE_ENDPOINT: https://ysgt36ldck.execute-api.eu-west-2.amazonaws.com/production/Favourites/update
      NEXT_PUBLIC_RETRIEVE_OFFER_ENDPOINT: https://h9to9ist4k.execute-api.eu-west-2.amazonaws.com/v1/offers/
      NEXT_PUBLIC_APP_MICROSERVICE_BRAND: BLC
      NEXT_PUBLIC_COGNITO_CLIENT_REGION: ${{matrix.region}}
      NEXT_PUBLIC_COGNITO_CLIENT_ID: ${{ secrets[matrix.cognito_client_id] }}
      NEXT_PUBLIC_COGNITO_CLIENT_SECRET: ${{ secrets[matrix.cognito_client_secret] }}
      NEXT_PUBLIC_FLAGSMITH_KEY: ${{ secrets.FLAGSMITH_KEY }}
      NEXT_PUBLIC_COGNITO_LOGIN_URL: https://auth.blcshine.io/login?client_id=7b854of9jqjte75vglfnm1gd3t&response_type=code&scope=aws.cognito.signin.user.admin+email+openid+profile&redirect_uri=https%3A%2F%2Fwww.bluelightcard.co.uk%2Fauth%2Fcallback.php
      NEXT_PUBLIC_COGNITO_LOGOUT_URL: https://auth.blcshine.io/logout?client_id=7b854of9jqjte75vglfnm1gd3t&response_type=code&scope=aws.cognito.signin.user.admin+email+openid+profile&redirect_uri=https%3A%2F%2Fwww.bluelightcard.co.uk%2Fauth%2Fcallback.php&logout_uri=https%3A%2F%2Fwww.bluelightcard.co.uk%2Flogout.php
      NEXT_PUBLIC_REDEMPTION_DETAILS_ENDPOINT: ${{ matrix.redemption_details_endpoint }}
      NEXT_PUBLIC_REDEEM_ENDPOINT: ${{ matrix.redeem_endpoint }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build shared-ui
        run: npm run build -w packages/shared-ui
      - name: remove mock login
        run: rm -rf packages/web/src/pages/mock-login.tsx
      - name: Build
        run: NEXT_PUBLIC_APP_BRAND=${{matrix.brand}} npm run build -w packages/web
      - name: Configure Headers
        run: cp packages/web/_headers packages/web/dist
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{matrix.brand}}
          branch: 'main'
          directory: packages/web/out
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
